var COMPILED=!0,goog=goog||{};goog.global=this;goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;goog.provide=function(a){if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a];for(var b=a;(b=b.substring(0,b.lastIndexOf(".")))&&!goog.getObjectByName(b);)goog.implicitNamespaces_[b]=!0}goog.exportPath_(a)};
goog.setTestOnly=function(a){if(COMPILED&&!goog.DEBUG)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};COMPILED||(goog.isProvided_=function(a){return!goog.implicitNamespaces_[a]&&!!goog.getObjectByName(a)},goog.implicitNamespaces_={});goog.exportPath_=function(a,b,c){a=a.split(".");c=c||goog.global;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&goog.isDef(b)?c[d]=b:c=c[d]?c[d]:c[d]={}};
goog.getObjectByName=function(a,b){for(var c=a.split("."),d=b||goog.global,f;f=c.shift();)if(goog.isDefAndNotNull(d[f]))d=d[f];else return null;return d};goog.globalize=function(a,b){var c=b||goog.global,d;for(d in a)c[d]=a[d]};
goog.addDependency=function(a,b,c){if(!COMPILED){var d;a=a.replace(/\\/g,"/");for(var f=goog.dependencies_,h=0;d=b[h];h++)f.nameToPath[d]=a,a in f.pathToNames||(f.pathToNames[a]={}),f.pathToNames[a][d]=!0;for(d=0;b=c[d];d++)a in f.requires||(f.requires[a]={}),f.requires[a][b]=!0}};goog.ENABLE_DEBUG_LOADER=!0;
goog.require=function(a){if(!COMPILED&&!goog.isProvided_(a)){if(goog.ENABLE_DEBUG_LOADER){var b=goog.getPathFromDeps_(a);if(b){goog.included_[b]=!0;goog.writeScripts_();return}}a="goog.require could not find: "+a;goog.global.console&&goog.global.console.error(a);throw Error(a);}};goog.basePath="";goog.nullFunction=function(){};goog.identityFunction=function(a,b){return a};goog.abstractMethod=function(){throw Error("unimplemented abstract method");};
goog.addSingletonGetter=function(a){a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];
!COMPILED&&goog.ENABLE_DEBUG_LOADER&&(goog.included_={},goog.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}},goog.inHtmlDocument_=function(){var a=goog.global.document;return"undefined"!=typeof a&&"write"in a},goog.findBasePath_=function(){if(goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_())for(var a=goog.global.document.getElementsByTagName("script"),b=a.length-1;0<=b;--b){var c=a[b].src,d=c.lastIndexOf("?"),d=
-1==d?c.length:d;if("base.js"==c.substr(d-7,7)){goog.basePath=c.substr(0,d-7);break}}},goog.importScript_=function(a){var b=goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_;!goog.dependencies_.written[a]&&b(a)&&(goog.dependencies_.written[a]=!0)},goog.writeScriptTag_=function(a){if(goog.inHtmlDocument_()){var b=goog.global.document;if("complete"==b.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}b.write('<script type="text/javascript" src="'+
a+'">\x3c/script>');return!0}return!1},goog.writeScripts_=function(){function a(f){if(!(f in d.written)){if(!(f in d.visited)&&(d.visited[f]=!0,f in d.requires))for(var g in d.requires[f])if(!goog.isProvided_(g))if(g in d.nameToPath)a(d.nameToPath[g]);else throw Error("Undefined nameToPath for "+g);f in c||(c[f]=!0,b.push(f))}}var b=[],c={},d=goog.dependencies_,f;for(f in goog.included_)d.written[f]||a(f);for(f=0;f<b.length;f++)if(b[f])goog.importScript_(goog.basePath+b[f]);else throw Error("Undefined script input");
},goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null},goog.findBasePath_(),goog.global.CLOSURE_NO_DEPS||goog.importScript_(goog.basePath+"deps.js"));
goog.typeOf=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};goog.isDef=function(a){return void 0!==a};goog.isNull=function(a){return null===a};goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return"array"==goog.typeOf(a)};goog.isArrayLike=function(a){var b=goog.typeOf(a);return"array"==b||"object"==b&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isString=function(a){return"string"==typeof a};
goog.isBoolean=function(a){return"boolean"==typeof a};goog.isNumber=function(a){return"number"==typeof a};goog.isFunction=function(a){return"function"==goog.typeOf(a)};goog.isObject=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};
goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if(a.clone)return a.clone();var b="array"==b?[]:{},c;for(c in a)b[c]=goog.cloneObject(a[c]);return b}return a};goog.bindNative_=function(a,b,c){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};goog.bind=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bind=goog.bindNative_:goog.bind=goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}};goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval)if(null==goog.evalWorksForGlobals_&&(goog.global.eval("var _et_ = 1;"),"undefined"!=typeof goog.global._et_?(delete goog.global._et_,goog.evalWorksForGlobals_=!0):goog.evalWorksForGlobals_=!1),goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=!1;c.appendChild(b.createTextNode(a));b.body.appendChild(c);
b.body.removeChild(c)}else throw Error("goog.globalEval not available");};goog.evalWorksForGlobals_=null;goog.getCssName=function(a,b){var c=function(a){return goog.cssNameMapping_[a]||a},d=function(a){a=a.split("-");for(var b=[],d=0;d<a.length;d++)b.push(c(a[d]));return b.join("-")},d=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?c:d:function(a){return a};return b?a+"-"+d(b):d(a)};goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};
!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,b){var c=b||{},d;for(d in c){var f=(""+c[d]).replace(/\$/g,"$$$$");a=a.replace(RegExp("\\{\\$"+d+"\\}","gi"),f)}return a};goog.getMsgWithFallback=function(a,b){return a};goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,c)};goog.exportProperty=function(a,b,c){a[b]=c};
goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a};
goog.base=function(a,b,c){var d=arguments.callee.caller;if(d.superClass_)return d.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var f=Array.prototype.slice.call(arguments,2),h=!1,g=a.constructor;g;g=g.superClass_&&g.superClass_.constructor)if(g.prototype[b]===d)h=!0;else if(h)return g.prototype[b].apply(a,f);if(a[b]===d)return a.constructor.prototype[b].apply(a,f);throw Error("goog.base called from a method of one name to a method of a different name");};
goog.scope=function(a){a.call(goog.global)};var hexgrid={hex:{}};function Hex(a,b,c){this.q=a;this.r=b;this.x=this.q;this.z=this.r;this.y=-this.x-this.z;this.size=c;this.color=[1,1,1,1];this.animationTime=this.animationFrame=this.texture=0;this.height=function(){return 2*this.size};this.width=function(){return 1.7320508*this.size};this.equals=function(a){return this.q===a.q&&this.r===a.r}};hexgrid.render={};hexgrid.render.shaders={};hexgrid.render.shaders.texture={};var texture_fs="varying highp vec2 vTexCoord;uniform sampler2D textureSampler;void main(void) {    gl_FragColor = texture2D(textureSampler, vec2(vTexCoord.s,vTexCoord.t));}",texture_vs="attribute vec3 aVertexPosition;attribute vec2 aTextureCoord;uniform mat4 uMVMatrix;uniform mat4 uPMatrix;varying highp vec2 vTexCoord;void main(void) {    gl_Position = uPMatrix * uMVMatrix * vec4(aVertexPosition, 1.0);    vTexCoord = aTextureCoord;}";hexgrid.render.shaders.basic={};var basic_fs="precision mediump float;varying vec4 vColor;void main(void) {    gl_FragColor = vColor;}",basic_vs="attribute vec3 aVertexPosition;attribute vec4 aVertexColor;uniform mat4 uMVMatrix;uniform mat4 uPMatrix;varying vec4 vColor;void main(void) {    gl_Position = uPMatrix * uMVMatrix * vec4(aVertexPosition, 1.0);    vColor = aVertexColor;}";var SHADER_TYPE_FRAG=1,SHADER_TYPE_VERT=2;var glmatrix={};glMatrixArrayType="undefined"!=typeof Float32Array?Float32Array:"undefined"!=typeof WebGLFloatArray?WebGLFloatArray:Array;
var vec3={create:function(a){var b=new glMatrixArrayType(3);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];return b},add:function(a,b,c){if(!c||a==c)return a[0]+=b[0],a[1]+=b[1],a[2]+=b[2],a;c[0]=a[0]+b[0];c[1]=a[1]+b[1];c[2]=a[2]+b[2];return c},subtract:function(a,b,c){if(!c||a==c)return a[0]-=b[0],a[1]-=b[1],a[2]-=b[2],a;c[0]=a[0]-b[0];c[1]=a[1]-b[1];c[2]=a[2]-b[2];return c},negate:function(a,b){b||(b=a);b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];return b},scale:function(a,
b,c){if(!c||a==c)return a[0]*=b,a[1]*=b,a[2]*=b,a;c[0]=a[0]*b;c[1]=a[1]*b;c[2]=a[2]*b;return c},normalize:function(a,b){b||(b=a);var c=a[0],d=a[1],f=a[2],h=Math.sqrt(c*c+d*d+f*f);if(h){if(1==h)return b[0]=c,b[1]=d,b[2]=f,b}else return b[0]=0,b[1]=0,b[2]=0,b;h=1/h;b[0]=c*h;b[1]=d*h;b[2]=f*h;return b},cross:function(a,b,c){c||(c=a);var d=a[0],f=a[1];a=a[2];var h=b[0],g=b[1];b=b[2];c[0]=f*b-a*g;c[1]=a*h-d*b;c[2]=d*g-f*h;return c},length:function(a){var b=a[0],c=a[1];a=a[2];return Math.sqrt(b*b+c*c+a*
a)},dot:function(a,b){return a[0]*b[0]+a[1]*b[1]+a[2]*b[2]},direction:function(a,b,c){c||(c=a);var d=a[0]-b[0],f=a[1]-b[1];a=a[2]-b[2];b=Math.sqrt(d*d+f*f+a*a);if(!b)return c[0]=0,c[1]=0,c[2]=0,c;b=1/b;c[0]=d*b;c[1]=f*b;c[2]=a*b;return c},lerp:function(a,b,c,d){d||(d=a);d[0]=a[0]+c*(b[0]-a[0]);d[1]=a[1]+c*(b[1]-a[1]);d[2]=a[2]+c*(b[2]-a[2]);return d},str:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+"]"}},mat3={create:function(a){var b=new glMatrixArrayType(9);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=
a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b[9]=a[9]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];return b},identity:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=1;a[5]=0;a[6]=0;a[7]=0;a[8]=1;return a},transpose:function(a,b){if(!b||a==b){var c=a[1],d=a[2],f=a[5];a[1]=a[3];a[2]=a[6];a[3]=c;a[5]=a[7];a[6]=d;a[7]=f;return a}b[0]=a[0];b[1]=a[3];b[2]=a[6];b[3]=a[1];b[4]=a[4];b[5]=a[7];b[6]=a[2];b[7]=a[5];b[8]=a[8];return b},
toMat4:function(a,b){b||(b=mat4.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=0;b[4]=a[3];b[5]=a[4];b[6]=a[5];b[7]=0;b[8]=a[6];b[9]=a[7];b[10]=a[8];b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},str:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+"]"}},mat4={create:function(a){var b=new glMatrixArrayType(16);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3],b[4]=a[4],b[5]=a[5],b[6]=a[6],b[7]=a[7],b[8]=a[8],b[9]=a[9],b[10]=a[10],b[11]=a[11],b[12]=
a[12],b[13]=a[13],b[14]=a[14],b[15]=a[15]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=a[12];b[13]=a[13];b[14]=a[14];b[15]=a[15];return b},identity:function(a){a[0]=1;a[1]=0;a[2]=0;a[3]=0;a[4]=0;a[5]=1;a[6]=0;a[7]=0;a[8]=0;a[9]=0;a[10]=1;a[11]=0;a[12]=0;a[13]=0;a[14]=0;a[15]=1;return a},transpose:function(a,b){if(!b||a==b){var c=a[1],d=a[2],f=a[3],h=a[6],g=a[7],k=a[11];a[1]=a[4];a[2]=
a[8];a[3]=a[12];a[4]=c;a[6]=a[9];a[7]=a[13];a[8]=d;a[9]=h;a[11]=a[14];a[12]=f;a[13]=g;a[14]=k;return a}b[0]=a[0];b[1]=a[4];b[2]=a[8];b[3]=a[12];b[4]=a[1];b[5]=a[5];b[6]=a[9];b[7]=a[13];b[8]=a[2];b[9]=a[6];b[10]=a[10];b[11]=a[14];b[12]=a[3];b[13]=a[7];b[14]=a[11];b[15]=a[15];return b},determinant:function(a){var b=a[0],c=a[1],d=a[2],f=a[3],h=a[4],g=a[5],k=a[6],e=a[7],l=a[8],n=a[9],m=a[10],r=a[11],p=a[12],s=a[13],q=a[14];a=a[15];return p*n*k*f-l*s*k*f-p*g*m*f+h*s*m*f+l*g*q*f-h*n*q*f-p*n*d*e+l*s*d*e+
p*c*m*e-b*s*m*e-l*c*q*e+b*n*q*e+p*g*d*r-h*s*d*r-p*c*k*r+b*s*k*r+h*c*q*r-b*g*q*r-l*g*d*a+h*n*d*a+l*c*k*a-b*n*k*a-h*c*m*a+b*g*m*a},inverse:function(a,b){b||(b=a);var c=a[0],d=a[1],f=a[2],h=a[3],g=a[4],k=a[5],e=a[6],l=a[7],n=a[8],m=a[9],r=a[10],p=a[11],s=a[12],q=a[13],t=a[14],u=a[15],x=c*k-d*g,y=c*e-f*g,w=c*l-h*g,z=d*e-f*k,A=d*l-h*k,B=f*l-h*e,C=n*q-m*s,D=n*t-r*s,E=n*u-p*s,F=m*t-r*q,G=m*u-p*q,H=r*u-p*t,v=1/(x*H-y*G+w*F+z*E-A*D+B*C);b[0]=(k*H-e*G+l*F)*v;b[1]=(-d*H+f*G-h*F)*v;b[2]=(q*B-t*A+u*z)*v;b[3]=
(-m*B+r*A-p*z)*v;b[4]=(-g*H+e*E-l*D)*v;b[5]=(c*H-f*E+h*D)*v;b[6]=(-s*B+t*w-u*y)*v;b[7]=(n*B-r*w+p*y)*v;b[8]=(g*G-k*E+l*C)*v;b[9]=(-c*G+d*E-h*C)*v;b[10]=(s*A-q*w+u*x)*v;b[11]=(-n*A+m*w-p*x)*v;b[12]=(-g*F+k*D-e*C)*v;b[13]=(c*F-d*D+f*C)*v;b[14]=(-s*z+q*y-t*x)*v;b[15]=(n*z-m*y+r*x)*v;return b},toRotationMat:function(a,b){b||(b=mat4.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];b[4]=a[4];b[5]=a[5];b[6]=a[6];b[7]=a[7];b[8]=a[8];b[9]=a[9];b[10]=a[10];b[11]=a[11];b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},
toMat3:function(a,b){b||(b=mat3.create());b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[4];b[4]=a[5];b[5]=a[6];b[6]=a[8];b[7]=a[9];b[8]=a[10];return b},toInverseMat3:function(a,b){var c=a[0],d=a[1],f=a[2],h=a[4],g=a[5],k=a[6],e=a[8],l=a[9],n=a[10],m=n*g-k*l,r=-n*h+k*e,p=l*h-g*e,s=c*m+d*r+f*p;if(!s)return null;s=1/s;b||(b=mat3.create());b[0]=m*s;b[1]=(-n*d+f*l)*s;b[2]=(k*d-f*g)*s;b[3]=r*s;b[4]=(n*c-f*e)*s;b[5]=(-k*c+f*h)*s;b[6]=p*s;b[7]=(-l*c+d*e)*s;b[8]=(g*c-d*h)*s;return b},multiply:function(a,b,c){c||(c=
a);var d=a[0],f=a[1],h=a[2],g=a[3],k=a[4],e=a[5],l=a[6],n=a[7],m=a[8],r=a[9],p=a[10],s=a[11],q=a[12],t=a[13],u=a[14];a=a[15];var x=b[0],y=b[1],w=b[2],z=b[3],A=b[4],B=b[5],C=b[6],D=b[7],E=b[8],F=b[9],G=b[10],H=b[11],v=b[12],I=b[13],J=b[14];b=b[15];c[0]=x*d+y*k+w*m+z*q;c[1]=x*f+y*e+w*r+z*t;c[2]=x*h+y*l+w*p+z*u;c[3]=x*g+y*n+w*s+z*a;c[4]=A*d+B*k+C*m+D*q;c[5]=A*f+B*e+C*r+D*t;c[6]=A*h+B*l+C*p+D*u;c[7]=A*g+B*n+C*s+D*a;c[8]=E*d+F*k+G*m+H*q;c[9]=E*f+F*e+G*r+H*t;c[10]=E*h+F*l+G*p+H*u;c[11]=E*g+F*n+G*s+H*a;
c[12]=v*d+I*k+J*m+b*q;c[13]=v*f+I*e+J*r+b*t;c[14]=v*h+I*l+J*p+b*u;c[15]=v*g+I*n+J*s+b*a;return c},multiplyVec3:function(a,b,c){c||(c=b);var d=b[0],f=b[1];b=b[2];c[0]=a[0]*d+a[4]*f+a[8]*b+a[12];c[1]=a[1]*d+a[5]*f+a[9]*b+a[13];c[2]=a[2]*d+a[6]*f+a[10]*b+a[14];return c},multiplyVec4:function(a,b,c){c||(c=b);var d=b[0],f=b[1],h=b[2];b=b[3];c[0]=a[0]*d+a[4]*f+a[8]*h+a[12]*b;c[1]=a[1]*d+a[5]*f+a[9]*h+a[13]*b;c[2]=a[2]*d+a[6]*f+a[10]*h+a[14]*b;c[3]=a[3]*d+a[7]*f+a[11]*h+a[15]*b;return c},translate:function(a,
b,c){var d=b[0],f=b[1];b=b[2];if(!c||a==c)return a[12]=a[0]*d+a[4]*f+a[8]*b+a[12],a[13]=a[1]*d+a[5]*f+a[9]*b+a[13],a[14]=a[2]*d+a[6]*f+a[10]*b+a[14],a[15]=a[3]*d+a[7]*f+a[11]*b+a[15],a;var h=a[0],g=a[1],k=a[2],e=a[3],l=a[4],n=a[5],m=a[6],r=a[7],p=a[8],s=a[9],q=a[10],t=a[11];c[0]=h;c[1]=g;c[2]=k;c[3]=e;c[4]=l;c[5]=n;c[6]=m;c[7]=r;c[8]=p;c[9]=s;c[10]=q;c[11]=t;c[12]=h*d+l*f+p*b+a[12];c[13]=g*d+n*f+s*b+a[13];c[14]=k*d+m*f+q*b+a[14];c[15]=e*d+r*f+t*b+a[15];return c},scale:function(a,b,c){var d=b[0],f=
b[1];b=b[2];if(!c||a==c)return a[0]*=d,a[1]*=d,a[2]*=d,a[3]*=d,a[4]*=f,a[5]*=f,a[6]*=f,a[7]*=f,a[8]*=b,a[9]*=b,a[10]*=b,a[11]*=b,a;c[0]=a[0]*d;c[1]=a[1]*d;c[2]=a[2]*d;c[3]=a[3]*d;c[4]=a[4]*f;c[5]=a[5]*f;c[6]=a[6]*f;c[7]=a[7]*f;c[8]=a[8]*b;c[9]=a[9]*b;c[10]=a[10]*b;c[11]=a[11]*b;c[12]=a[12];c[13]=a[13];c[14]=a[14];c[15]=a[15];return c},rotate:function(a,b,c,d){var f=c[0],h=c[1];c=c[2];var g=Math.sqrt(f*f+h*h+c*c);if(!g)return null;1!=g&&(g=1/g,f*=g,h*=g,c*=g);var k=Math.sin(b),e=Math.cos(b),l=1-e;
b=a[0];var g=a[1],n=a[2],m=a[3],r=a[4],p=a[5],s=a[6],q=a[7],t=a[8],u=a[9],x=a[10],y=a[11],w=f*f*l+e,z=h*f*l+c*k,A=c*f*l-h*k,B=f*h*l-c*k,C=h*h*l+e,D=c*h*l+f*k,E=f*c*l+h*k,f=h*c*l-f*k,h=c*c*l+e;d?a!=d&&(d[12]=a[12],d[13]=a[13],d[14]=a[14],d[15]=a[15]):d=a;d[0]=b*w+r*z+t*A;d[1]=g*w+p*z+u*A;d[2]=n*w+s*z+x*A;d[3]=m*w+q*z+y*A;d[4]=b*B+r*C+t*D;d[5]=g*B+p*C+u*D;d[6]=n*B+s*C+x*D;d[7]=m*B+q*C+y*D;d[8]=b*E+r*f+t*h;d[9]=g*E+p*f+u*h;d[10]=n*E+s*f+x*h;d[11]=m*E+q*f+y*h;return d},rotateX:function(a,b,c){var d=Math.sin(b);
b=Math.cos(b);var f=a[4],h=a[5],g=a[6],k=a[7],e=a[8],l=a[9],n=a[10],m=a[11];c?a!=c&&(c[0]=a[0],c[1]=a[1],c[2]=a[2],c[3]=a[3],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[4]=f*b+e*d;c[5]=h*b+l*d;c[6]=g*b+n*d;c[7]=k*b+m*d;c[8]=f*-d+e*b;c[9]=h*-d+l*b;c[10]=g*-d+n*b;c[11]=k*-d+m*b;return c},rotateY:function(a,b,c){var d=Math.sin(b);b=Math.cos(b);var f=a[0],h=a[1],g=a[2],k=a[3],e=a[8],l=a[9],n=a[10],m=a[11];c?a!=c&&(c[4]=a[4],c[5]=a[5],c[6]=a[6],c[7]=a[7],c[12]=a[12],c[13]=a[13],c[14]=a[14],
c[15]=a[15]):c=a;c[0]=f*b+e*-d;c[1]=h*b+l*-d;c[2]=g*b+n*-d;c[3]=k*b+m*-d;c[8]=f*d+e*b;c[9]=h*d+l*b;c[10]=g*d+n*b;c[11]=k*d+m*b;return c},rotateZ:function(a,b,c){var d=Math.sin(b);b=Math.cos(b);var f=a[0],h=a[1],g=a[2],k=a[3],e=a[4],l=a[5],n=a[6],m=a[7];c?a!=c&&(c[8]=a[8],c[9]=a[9],c[10]=a[10],c[11]=a[11],c[12]=a[12],c[13]=a[13],c[14]=a[14],c[15]=a[15]):c=a;c[0]=f*b+e*d;c[1]=h*b+l*d;c[2]=g*b+n*d;c[3]=k*b+m*d;c[4]=f*-d+e*b;c[5]=h*-d+l*b;c[6]=g*-d+n*b;c[7]=k*-d+m*b;return c},frustum:function(a,b,c,d,
f,h,g){g||(g=mat4.create());var k=b-a,e=d-c,l=h-f;g[0]=2*f/k;g[1]=0;g[2]=0;g[3]=0;g[4]=0;g[5]=2*f/e;g[6]=0;g[7]=0;g[8]=(b+a)/k;g[9]=(d+c)/e;g[10]=-(h+f)/l;g[11]=-1;g[12]=0;g[13]=0;g[14]=-(2*h*f)/l;g[15]=0;return g},perspective:function(a,b,c,d,f){a=c*Math.tan(a*Math.PI/360);b*=a;return mat4.frustum(-b,b,-a,a,c,d,f)},ortho:function(a,b,c,d,f,h,g){g||(g=mat4.create());var k=b-a,e=d-c,l=h-f;g[0]=2/k;g[1]=0;g[2]=0;g[3]=0;g[4]=0;g[5]=2/e;g[6]=0;g[7]=0;g[8]=0;g[9]=0;g[10]=-2/l;g[11]=0;g[12]=-(a+b)/k;g[13]=
-(d+c)/e;g[14]=-(h+f)/l;g[15]=1;return g},lookAt:function(a,b,c,d){d||(d=mat4.create());var f=a[0],h=a[1];a=a[2];var g=c[0],k=c[1],e=c[2];c=b[1];var l=b[2];if(f==b[0]&&h==c&&a==l)return mat4.identity(d);var n,m,r,p;c=f-b[0];l=h-b[1];b=a-b[2];p=1/Math.sqrt(c*c+l*l+b*b);c*=p;l*=p;b*=p;n=k*b-e*l;e=e*c-g*b;g=g*l-k*c;(p=Math.sqrt(n*n+e*e+g*g))?(p=1/p,n*=p,e*=p,g*=p):g=e=n=0;k=l*g-b*e;m=b*n-c*g;r=c*e-l*n;(p=Math.sqrt(k*k+m*m+r*r))?(p=1/p,k*=p,m*=p,r*=p):r=m=k=0;d[0]=n;d[1]=k;d[2]=c;d[3]=0;d[4]=e;d[5]=m;
d[6]=l;d[7]=0;d[8]=g;d[9]=r;d[10]=b;d[11]=0;d[12]=-(n*f+e*h+g*a);d[13]=-(k*f+m*h+r*a);d[14]=-(c*f+l*h+b*a);d[15]=1;return d},str:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+", "+a[4]+", "+a[5]+", "+a[6]+", "+a[7]+", "+a[8]+", "+a[9]+", "+a[10]+", "+a[11]+", "+a[12]+", "+a[13]+", "+a[14]+", "+a[15]+"]"}};
quat4={create:function(a){var b=new glMatrixArrayType(4);a&&(b[0]=a[0],b[1]=a[1],b[2]=a[2],b[3]=a[3]);return b},set:function(a,b){b[0]=a[0];b[1]=a[1];b[2]=a[2];b[3]=a[3];return b},calculateW:function(a,b){var c=a[0],d=a[1],f=a[2];if(!b||a==b)return a[3]=-Math.sqrt(Math.abs(1-c*c-d*d-f*f)),a;b[0]=c;b[1]=d;b[2]=f;b[3]=-Math.sqrt(Math.abs(1-c*c-d*d-f*f));return b},inverse:function(a,b){if(!b||a==b)return a[0]*=1,a[1]*=1,a[2]*=1,a;b[0]=-a[0];b[1]=-a[1];b[2]=-a[2];b[3]=a[3];return b},length:function(a){var b=
a[0],c=a[1],d=a[2];a=a[3];return Math.sqrt(b*b+c*c+d*d+a*a)},normalize:function(a,b){b||(b=a);var c=a[0],d=a[1],f=a[2],h=a[3],g=Math.sqrt(c*c+d*d+f*f+h*h);if(0==g)return b[0]=0,b[1]=0,b[2]=0,b[3]=0,b;g=1/g;b[0]=c*g;b[1]=d*g;b[2]=f*g;b[3]=h*g;return b},multiply:function(a,b,c){c||(c=a);var d=a[0],f=a[1],h=a[2];a=a[3];var g=b[0],k=b[1],e=b[2];b=b[3];c[0]=d*b+a*g+f*e-h*k;c[1]=f*b+a*k+h*g-d*e;c[2]=h*b+a*e+d*k-f*g;c[3]=a*b-d*g-f*k-h*e;return c},multiplyVec3:function(a,b,c){c||(c=b);var d=b[0],f=b[1],h=
b[2];b=a[0];var g=a[1],k=a[2];a=a[3];var e=a*d+g*h-k*f,l=a*f+k*d-b*h,n=a*h+b*f-g*d,d=-b*d-g*f-k*h;c[0]=e*a+d*-b+l*-k-n*-g;c[1]=l*a+d*-g+n*-b-e*-k;c[2]=n*a+d*-k+e*-g-l*-b;return c},toMat3:function(a,b){b||(b=mat3.create());var c=a[0],d=a[1],f=a[2],h=a[3],g=c+c,k=d+d,e=f+f,l=c*g,n=c*k,c=c*e,m=d*k,d=d*e,f=f*e,g=h*g,k=h*k,h=h*e;b[0]=1-(m+f);b[1]=n-h;b[2]=c+k;b[3]=n+h;b[4]=1-(l+f);b[5]=d-g;b[6]=c-k;b[7]=d+g;b[8]=1-(l+m);return b},toMat4:function(a,b){b||(b=mat4.create());var c=a[0],d=a[1],f=a[2],h=a[3],
g=c+c,k=d+d,e=f+f,l=c*g,n=c*k,c=c*e,m=d*k,d=d*e,f=f*e,g=h*g,k=h*k,h=h*e;b[0]=1-(m+f);b[1]=n-h;b[2]=c+k;b[3]=0;b[4]=n+h;b[5]=1-(l+f);b[6]=d-g;b[7]=0;b[8]=c-k;b[9]=d+g;b[10]=1-(l+m);b[11]=0;b[12]=0;b[13]=0;b[14]=0;b[15]=1;return b},slerp:function(a,b,c,d){d||(d=a);var f=c;0>a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3]&&(f=-1*c);d[0]=1-c*a[0]+f*b[0];d[1]=1-c*a[1]+f*b[1];d[2]=1-c*a[2]+f*b[2];d[3]=1-c*a[3]+f*b[3];return d},str:function(a){return"["+a[0]+", "+a[1]+", "+a[2]+", "+a[3]+"]"}};hexgrid.render.camera={};
function HexCamera(a){function b(){var a=mat4.create();mat4.identity(a);mat4.translate(a,[-g,-k,-e]);mat4.rotate(a,l*Math.PI/180,[1,0,0],a);return a}function c(){var a=mat4.create();mat4.identity(a);mat4.perspective(h/2,f.viewportWidth/f.viewportHeight,0.1,1E3,a);return a}function d(a,b,c){g+=a;k+=b;e+=c}var f=a,h=90,g=47,k=12,e=50,l=-30;return{moveX:function(a){d(a,0,0)},moveY:function(a){d(0,a,0)},moveZ:function(a){d(0,0,a)},move:d,getPos:function(){return[g,k,e]},adjustAngleDegrees:function(a){l+=a},
getViewMatrix:b,getProjectionMatrix:c,unprojectPoint:function(a,d){var e,g,l=mat4.create(),h=mat4.create();mat4.identity(l);e=b();g=c();mat4.multiply(g,e,h);mat4.inverse(h,l);e=[];e[0]=2*((a-f.viewportX)/f.viewportWidth)-1;e[1]=2*((d-f.viewportY)/f.viewportHeight)-1;e[2]=-1;e[3]=1;g=[];g[0]=2*((a-f.viewportX)/f.viewportWidth)-1;g[1]=2*((d-f.viewportY)/f.viewportHeight)-1;g[2]=1;g[3]=1;var h=[0,0,0,0],k=[0,0,0,0];mat4.multiply(l,e,h);if(0==h[3])return console.log("unproject point resulted in 0 for w coordinate. Does this ever happen?"),
null;h[3]=1/h[3];h[0]*=h[3];h[1]*=h[3];h[2]*=h[3];mat4.multiply(l,g,k);if(0==k[3])return console.log("unproject point resulted in 0 for w coordinate. Does this ever happen?"),null;k[3]=1/k[3];k[0]*=k[3];k[1]*=k[3];k[2]*=k[3];return[[h[0],h[1],h[2]],[k[0],k[1],k[2]]]}}};hexgrid.render.renderengine={};
function HexRenderEngine(a){function b(a,b){if(!a)return null;var c;if(b===SHADER_TYPE_FRAG)c=e.createShader(e.FRAGMENT_SHADER);else if(b===SHADER_TYPE_VERT)c=e.createShader(e.VERTEX_SHADER);else return null;e.shaderSource(c,a);e.compileShader(c);return e.getShaderParameter(c,e.COMPILE_STATUS)?c:(alert(e.getShaderInfoLog(c)),null)}function c(a){e.uniformMatrix4fv(a.pMatrixUniform,!1,s);e.uniformMatrix4fv(a.mvMatrixUniform,!1,p)}function d(){w.map(function(a,b){var c=new Image,d={};c.onload=function(){var a=
e.createTexture();x[b]=a;e.bindTexture(e.TEXTURE_2D,a);e.pixelStorei(e.UNPACK_FLIP_Y_WEBGL,1);e.texImage2D(e.TEXTURE_2D,0,e.RGBA,e.RGBA,e.UNSIGNED_BYTE,c);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_MIN_FILTER,e.LINEAR);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_WRAP_S,e.CLAMP_TO_EDGE);e.texParameteri(e.TEXTURE_2D,e.TEXTURE_WRAP_T,e.CLAMP_TO_EDGE);y--;e.bindTexture(e.TEXTURE_2D,null);d.createdTexture=void 0};c.src=a;return d})}function f(a){s=u.getProjectionMatrix();for(var b=0;b<a.length;++b){var d=a[b],
f=d.width()*(d.q+d.r/2),g=3*d.height()*d.r/4;3==d.texture&&(d.animationTime++,10<d.animationTime&&(d.animationTime=0,d.animationFrame=++d.animationFrame%7));var h=d.color,k=d.texture,w=d.animationFrame,d=d.size;p=u.getViewMatrix();mat4.translate(p,[f,g,0]);mat4.scale(p,[2*d,2*d,1]);0<k?(h=x[3==k?k+w-1:k-1],e.useProgram(t),e.activeTexture(e.TEXTURE0),e.bindTexture(e.TEXTURE_2D,h),e.uniform1i(t.textureSampler,0),e.enableVertexAttribArray(t.textureCoordAttribute),e.bindBuffer(e.ARRAY_BUFFER,r),e.vertexAttribPointer(t.textureCoordAttribute,
r.itemSize,e.FLOAT,!1,0,0),e.enableVertexAttribArray(t.vertexPositionAttribute),e.bindBuffer(e.ARRAY_BUFFER,l),e.vertexAttribPointer(t.vertexPositionAttribute,l.itemSize,e.FLOAT,!1,0,0),e.bindBuffer(e.ELEMENT_ARRAY_BUFFER,n),c(t),e.drawElements(e.TRIANGLES,18,e.UNSIGNED_SHORT,0),e.disableVertexAttribArray(t.textureCoordAttribute),e.bindBuffer(e.ELEMENT_ARRAY_BUFFER,null),e.bindBuffer(e.ARRAY_BUFFER,null),e.bindTexture(e.TEXTURE_2D,null)):(e.useProgram(q),e.vertexAttrib4fv(q.vertexColorAttribute,new Float32Array(h)),
e.bindBuffer(e.ARRAY_BUFFER,l),e.vertexAttribPointer(q.vertexPositionAttribute,l.itemSize,e.FLOAT,!1,0,0),e.enableVertexAttribArray(q.vertexPositionAttribute),e.bindBuffer(e.ELEMENT_ARRAY_BUFFER,n),c(q),e.drawElements(e.TRIANGLES,18,e.UNSIGNED_SHORT,0),e.bindBuffer(e.ELEMENT_ARRAY_BUFFER,null),e.bindBuffer(e.ARRAY_BUFFER,null));e.useProgram(q);e.bindBuffer(e.ARRAY_BUFFER,m);e.vertexAttrib4fv(q.vertexColorAttribute,new Float32Array([0,0,1,1]));c(q);e.vertexAttribPointer(q.vertexPositionAttribute,m.itemSize,
e.FLOAT,!1,0,0);e.enableVertexAttribArray(q.vertexPositionAttribute);e.drawArrays(e.LINE_STRIP,0,m.numItems);e.bindBuffer(e.ARRAY_BUFFER,null)}}function h(){e.clearColor(0,0,0,1);e.viewportX=0;e.viewportY=0;e.viewport(e.viewportX,e.viewportY,e.viewportWidth,e.viewportHeight);e.clear(e.COLOR_BUFFER_BIT|e.DEPTH_BUFFER_BIT)}function g(a,b){b=e.viewportHeight-b;var c=u.unprojectPoint(a,b),d=c[0],c=c[1],d=[d[0]-c[0],d[1]-c[1],d[2]-c[2]],f=-c[2]/d[2];return[c[0]+f*d[0],c[1]+f*d[1]]}function k(){return w.length}
var e=void 0,l,n,m,r,p=mat4.create(),s=mat4.create(),q,t,u,x={},y=9,w="img/test.png img/test2.png img/pie0.png img/pie1.png img/pie2.png img/pie3.png img/pie4.png img/pie5.png img/pie6.png".split(" ");(function(){for(var c=["webgl","experimental-webgl","moz-webgl","webkit-3d"],f=0;f<c.length;f++){try{if(e=a.getContext(c[f]))break}catch(g){console.log("WebGL is not supported by this configuration: "+c[f])}void 0===e&&console.log("WebGL is not supported by this configuration: "+c[f])}try{e.viewportWidth=
a.width,e.viewportHeight=a.height}catch(h){console.log(h.message)}c=b(basic_fs,SHADER_TYPE_FRAG);f=b(basic_vs,SHADER_TYPE_VERT);q=e.createProgram();e.attachShader(q,f);e.attachShader(q,c);e.linkProgram(q);e.getProgramParameter(q,e.LINK_STATUS)||alert("Could not initialise shaders");e.useProgram(q);q.vertexPositionAttribute=e.getAttribLocation(q,"aVertexPosition");q.vertexColorAttribute=e.getAttribLocation(q,"aVertexColor");q.pMatrixUniform=e.getUniformLocation(q,"uPMatrix");q.mvMatrixUniform=e.getUniformLocation(q,
"uMVMatrix");c=b(texture_fs,SHADER_TYPE_FRAG);f=b(texture_vs,SHADER_TYPE_VERT);t=e.createProgram();e.attachShader(t,f);e.attachShader(t,c);e.linkProgram(t);e.getProgramParameter(t,e.LINK_STATUS)||alert("Could not initialise shaders");e.useProgram(t);t.vertexPositionAttribute=e.getAttribLocation(t,"aVertexPosition");t.pMatrixUniform=e.getUniformLocation(t,"uPMatrix");t.mvMatrixUniform=e.getUniformLocation(t,"uMVMatrix");t.textureCoordAttribute=e.getAttribLocation(t,"aTextureCoord");t.textureSampler=
e.getUniformLocation(t,"textureSampler");d();l=e.createBuffer();m=e.createBuffer();r=e.createBuffer();for(var c=[0,0,0],f=[0.5,0.5],k=[],p=0;6>=p;p++){var s=2*Math.PI/6*(0.5-p),u=0.5*Math.cos(s),s=0.5*Math.sin(s);c.push(u);c.push(s);c.push(0);k.push(u);k.push(s);k.push(0.01);f.push(u+0.5);f.push(s+0.5)}c.push(0.5*Math.cos(2*Math.PI/3));c.push(0.5*Math.sin(2*Math.PI/3));c.push(0);f.push(0.5+0.5*Math.cos(2*Math.PI/3));f.push(0.5+0.5*Math.sin(2*Math.PI/3));k.push(k[0]);k.push(k[1]);k.push(0);n=e.createBuffer();
e.bindBuffer(e.ELEMENT_ARRAY_BUFFER,n);e.bufferData(e.ELEMENT_ARRAY_BUFFER,new Uint16Array([0,1,2,0,2,3,0,3,4,0,4,5,0,5,6,0,6,1]),e.STATIC_DRAW);e.bindBuffer(e.ARRAY_BUFFER,l);e.bufferData(e.ARRAY_BUFFER,new Float32Array(c),e.STATIC_DRAW);l.itemSize=3;l.numItems=8;e.bindBuffer(e.ARRAY_BUFFER,r);e.bufferData(e.ARRAY_BUFFER,new Float32Array(f),e.STATIC_DRAW);r.itemSize=2;r.numItems=8;e.bindBuffer(e.ARRAY_BUFFER,m);e.bufferData(e.ARRAY_BUFFER,new Float32Array(k),e.STATIC_DRAW);m.itemSize=3;m.numItems=
7;e.enable(e.DEPTH_TEST);e.depthFunc(e.LEQUAL)})();if(e)return u=new HexCamera(e),{camera:u,drawHexes:f,clearCanvas:h,projectScreenCoordToXYPlane:g,numTextures:k};alert("you do not support!")};hexgrid.player={};function Player(a){function b(){var b=a.getCanvasSize();return a.findByPixel(b[0]/2,b[1]/2)}var c;return{tick:function(){c&&(c.color=[1,1,1,1]);if(c=b())c.color=[1,0,0,1]},currentLocation:b}};hexgrid.ai={};hexgrid.ai.patrol={};
function PatrolAI(a,b,c){function d(a){for(var b=0;b<h.length;++b)h[b].color=a}function f(b){d(n);var c=h[k];h=a.getPath(c,b);d(l);c.color=m;k=0}var h=a.getLine(b,c),g=(new Date).getTime(),k=0,e=1,l=[0.8,0.8,0.8,1],n=[1,1,1,1],m=[0.5,0.3,0.3,1],r=[0.3,0,0,1],p=!1;return{tick:function(){if(p)d(n),h[k].color=r;else if(300<(new Date).getTime()-g){h[k].color=l;k+=e;if(k>h.length-1||0>k)e=-e,k+=e;h[k].color=m;g=(new Date).getTime()}},setNewPatrolPath:f,reCalculatePath:function(){p||(h[k].color=n,k=0,f(h[h.length-
1]))},posHex:function(){return h[k]},die:function(){p=!0}}};hexgrid.ai.astar={};
function AStarPathFinderFactory(a,b){function c(a,b){for(var c=0;c<a.length;c++)if(a[c].equals(b))return!0;return!1}function d(a){a.g=0;a.h=0;a.parent=null;a.f=0}return{findPath:function(f,h){var g=[],k=[];for(g.push(f);0<g.length;){for(var e=0,l=0;l<g.length;l++)g[l].f<g[e].f&&(e=l);e=g[e];if(e.equals(h)){g=e;for(k=[];g.parent;)k.push(g),g=g.parent;k.push(f);g=k.reverse();a.applyToAllHexes(d);return g}a:for(var l=g,n=e,m=0;m<l.length;m++)if(l[m].equals(n)){l.splice(m,1);break a}k.push(e);n=a.findNeighbors(e);
for(l=0;l<n.length;l++)if(m=n[l],!c(k,m)&&!hexBlocked(m)){void 0==e.g&&(e.g=0);var r=e.g+1,p=!1;c(g,m)?r<m.g&&(p=!0):(p=!0,m.h=b(m,h),g.push(m));p&&(m.parent=e,m.g=r,m.f=m.g+m.h)}}}}};hexgrid.util={};function Vector(a,b,c){this.x=a;this.y=b;this.z=c}function convertXYZtoQR(a,b,c){this.q=a;this.r=c};function HexGrid(a,b){function c(a){var b=new Hex(a.x,a.y,d);h[b.q+"_"+b.r]={hex:b,tile:a};f.push(b)}var d=10,f=[],h={},g=null,k=new HexRenderEngine(a,b);this.numTextures=function(){return k.numTextures()};this.loop=function(){this.update();this.renderOneFrame()};this.getCanvasSize=function(){return[a.width,a.height]};this.getLine=function(a,b){for(var c=this.vectorDistanceBetween(a,b),d=this.scalarDistance(a,b),e=[],f=0;f<d;f++){var g=f/d,h=Math.round(c.x*g),k=Math.round(c.y*g),g=Math.round(c.z*
g),h=new convertXYZtoQR(a.x+h,a.y+k,a.z+g);(h=this.find(h.q,h.r))&&e.push(h)}return e};this.vectorDistanceBetween=function(a,b){return{x:b.x-a.x,y:b.y-a.y,z:b.z-a.z}};this.scalarDistance=function(a,b){var c=Math.abs,d=a.y,e=a.z,f=b.y,g=b.z;return(c(a.x-b.x)+c(d-f)+c(e-g))/2};this.loadMap=function(a){g=a;a.forEach(c)};this.getMap=function(){return g};this.draw=function(){k.drawHexes(f)};this.clear=function(){k.clearCanvas()};this.findByPixel=function(a,b){var c,e;c=k.projectScreenCoordToXYPlane(a,
b);a=c[0];b=c[1];e=a;c=b;e=(1/3*Math.sqrt(3)*e-1/3*c)/d;var f=2/3*c/d;c=Math.round(e);e=Math.round(f);return this.find(c,e)};this.find=function(a,b){var c=h[a+"_"+b];return c?c.hex:null};this.remove=function(a,b){var c=a+"_"+b;h[c]&&(h[c]=null);for(var c=new Hex(a,b,d),e=0;e<f.length;++e)if(f[e].equals(c)){f.splice(e,1);break}};this.removeAll=function(){f=[];g={}};this.applyToAllHexes=function(a){if("function"===typeof a)for(var b=0;b<f.length;++b)a(f[b])};this.renderOneFrame=function(){this.clear();
this.draw()};var e=[[1,0],[1,-1],[0,-1],[-1,0],[-1,1],[0,1]];this.getNeighbor=function(a,b){return this.find(a.q+e[b][0],a.r+e[b][1])};this.findNeighbors=function(a){for(var b=[],c=0;c<e.length;++c){var d=this.getNeighbor(a,c);d&&b.push(d)}return b};this.getRing=function(a,b){for(var c=a.q-b,d=a.r+b,f=[],g=0;g<e.length;++g)for(var h=0;h<b;++h){var k=this.find(c,d);k&&f.push(k);c+=e[g][0];d+=e[g][1]}return f};this.getRange=function(a,b){for(var c=[a],d=-b;d<=b;++d)for(var e=Math.max(-b,-d-b);e<=Math.min(b,
-d+b);++e){var f=this.find(a.x+d,a.z+(-d-e));f&&c.push(f)}return c};this.getRangeIntersection=function(a,b,c,d){a=this.getRange(a,b);c=this.getRange(c,d);d=[];for(b=0;b<a.length;++b)for(var e=0;e<c.length;++e)a[b].equals(c[e])&&d.push(a[b]);return d};this.update=function(){};this.getCamera=function(){return k.camera};this.getPath=AStarPathFinderFactory(this,function(){return 1}).findPath};
